name: Keep Supabase Alive

on:
  schedule:
    # Menjalankan aksi ini setiap 2 hari sekali pada jam 00:00 UTC (07:00 WIB)
    - cron: '0 0 */2 * *'
  workflow_dispatch: # Memungkinkan kita menjalankan aksi ini secara manual jika diperlukan

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase REST API
        run: |
          echo "Pinging Supabase to keep it awake..."
          curl -s -o /dev/null -w "%{http_code}" -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJveGFucmNsdGtwb3pvYW5jb2hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY4MjE3MTYsImV4cCI6MjEwMjM5NzcxNn0.h4HKmfxh2oaHXtj_XUwgwLN4ujRpNwP3VyBi40gTRHk" \
               -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJveGFucmNsdGtwb3pvYW5jb2hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY4MjE3MTYsImV4cCI6MjEwMjM5NzcxNn0.h4HKmfxh2oaHXtj_XUwgwLN4ujRpNwP3VyBi40gTRHk" \
               "https://boxanrcltkpozoancohs.supabase.co/rest/v1/products?select=id&limit=1"
          echo "Ping finished!"
