name: Keep Supabase Alive

on:
  schedule:
    # Menjalankan aksi ini setiap 2 hari sekali pada jam 00:00 UTC (07:00 WIB)
    - cron: '0 0 */2 * *'
  workflow_dispatch: # Memungkinkan kita menjalankan aksi ini secara manual jika diperlukan

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase REST API
        run: |
          echo "Pinging Supabase to keep it awake..."
          curl -s -o /dev/null -w "%{http_code}" -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6d2ZzaGFsbG54c3diYnRnaHpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAxMzQzNTMsImV4cCI6MjEwNTcxMDM1M30.hsz3DPGqy6-c2a0JwZqS2IAASHhObE7dcTMM88YV6nY" \
               -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6d2ZzaGFsbG54c3diYnRnaHpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAxMzQzNTMsImV4cCI6MjEwNTcxMDM1M30.hsz3DPGqy6-c2a0JwZqS2IAASHhObE7dcTMM88YV6nY" \
               "https://azwfshallnxswbbtghzn.supabase.co/rest/v1/products?select=id&limit=1"
          echo "Ping finished!"
